// ============================================================
// tb_top — UVM Testbench Top (VCS)
// ============================================================
// Architecture:
//   - clk_gen ×2 → clk_a, clk_b (independent freq/phase/jitter)
//   - mem_port_if port_a(clk_a), port_b(clk_b)
//   - `include "gen/all_connect.sv" → DUT ori+new pairs
//   - sram_ref_model (functional check)
//   - mem_port_checker ×2 (SVA, per-port)
//   - UVM config_db + run_test()
//
// Runtime:
//   +UVM_TESTNAME=test_mem_sp
//   +ADDR_WIDTH=10 +DATA_WIDTH=32
//   +CLK_PERIOD_PS=10000 (both clk_a and clk_b)
// ============================================================

`timescale 1ns/1ps

import uvm_pkg::*;
`include "uvm_macros.svh"
import mem_uvc_pkg::*;
import mem_test_pkg::*;

module tb_top;

    localparam MAX_ADDR_WIDTH = 16;
    localparam MAX_DATA_WIDTH = 256;
    localparam READ_LATENCY    = 1;

    // ----------------------------------------------------------
    // Clocks & Reset
    // ----------------------------------------------------------
    logic clk_a, clk_b, clk_stable_a, clk_stable_b, rst_n;

    logic gate_a, gate_b;
    assign gate_a = 1'b1;  // always on
    assign gate_b = 1'b1;

    clk_gen #(.PERIOD_PS(10000), .SEED(42)) u_clk_a (
        .gate_en    (gate_a),
        .clk        (clk_a),
        .clk_stable (clk_stable_a)
    );
    clk_gen #(.PERIOD_PS(10000), .SEED(99)) u_clk_b (
        .gate_en    (gate_b),
        .clk        (clk_b),
        .clk_stable (clk_stable_b)
    );

    assign clk_stable = clk_stable_a && clk_stable_b;

    initial begin
        rst_n = 1'b0;
        @(posedge clk_stable);
        repeat (5) @(posedge clk_a);
        rst_n = 1'b1;
    end

    // ----------------------------------------------------------
    // Decoupled Port Interfaces
    // ----------------------------------------------------------
    mem_port_if #(MAX_ADDR_WIDTH, MAX_DATA_WIDTH) port_a(.clk(clk_a), .rst_n(rst_n));
    mem_port_if #(MAX_ADDR_WIDTH, MAX_DATA_WIDTH) port_b(.clk(clk_b), .rst_n(rst_n));

    // ----------------------------------------------------------
    // Runtime Configuration
    // ----------------------------------------------------------
    int cfg_addr_width = 10;
    int cfg_data_width = 32;
    logic [MAX_ADDR_WIDTH-1:0] addr_mask;
    logic [MAX_DATA_WIDTH-1:0] data_mask;
    logic [MAX_DATA_WIDTH-1:0] wem_mask;

    initial begin
        void'($value$plusargs("ADDR_WIDTH=%d", cfg_addr_width));
        void'($value$plusargs("DATA_WIDTH=%d", cfg_data_width));
        addr_mask = (1 << cfg_addr_width) - 1;
        data_mask = (1 << cfg_data_width) - 1;
        wem_mask  = (1 << cfg_data_width) - 1;
    end

    // ----------------------------------------------------------
    // DUTs (A/B Test) — auto-generated by gen_sram_b2b.py
    // ----------------------------------------------------------
    `include "gen/all_connect.sv"

    // ----------------------------------------------------------
    // Reference Model
    // ----------------------------------------------------------
    sram_ref_model #(MAX_ADDR_WIDTH, MAX_DATA_WIDTH, READ_LATENCY) u_ref (
        .clk    (clk_a),
        .rst_n  (rst_n),
        .web_a  (port_a.web),
        .addr_a (port_a.addr),
        .wdata_a(port_a.wdata),
        .wem_a  (port_a.wem),
        .rdata_a_ref (port_a.rdata_ref),
        .web_b  (port_b.web),
        .addr_b (port_b.addr),
        .wdata_b(port_b.wdata),
        .wem_b  (port_b.wem),
        .rdata_b_ref (port_b.rdata_ref)
    );

    // ----------------------------------------------------------
    // SVA Checkers (per-port)
    // ----------------------------------------------------------
    mem_port_checker #(MAX_DATA_WIDTH, READ_LATENCY, 1, "A") checker_a (
        .vif       (port_a.monitor),
        .data_mask (data_mask)
    );

    mem_port_checker #(MAX_DATA_WIDTH, READ_LATENCY, 1, "B") checker_b (
        .vif       (port_b.monitor),
        .data_mask (data_mask)
    );

    // ----------------------------------------------------------
    // Waveform Dump
    // ----------------------------------------------------------
    initial begin
        $dumpfile("dump.fst");
        $dumpvars(0, tb_top);
    end

    // ----------------------------------------------------------
    // UVM Configuration & Test Start
    // ----------------------------------------------------------
    string test_name;
    initial begin
        // Set virtual interfaces in config_db
        uvm_config_db #(virtual mem_port_if #(MAX_ADDR_WIDTH, MAX_DATA_WIDTH))::set(
            null, "uvm_test_top.*", "port_a_vif", port_a);
        uvm_config_db #(virtual mem_port_if #(MAX_ADDR_WIDTH, MAX_DATA_WIDTH))::set(
            null, "uvm_test_top.*", "port_b_vif", port_b);

        // Run UVM test
        if ($value$plusargs("UVM_TESTNAME=%s", test_name))
            run_test(test_name);
        else
            run_test("test_mem_sp");

        // Pass vif via config_db only for now
        $display("[TB_TOP] config_db set done, aw=%0d dw=%0d", cfg_addr_width, cfg_data_width);
    end

endmodule
