#!/usr/bin/env python3
# ============================================================
# gen_sram_b2b.py - SRAM Back-to-Back 文件自动生成器
# ============================================================
# 解决痛点: 当 original 和 replacement SRAM 具有相同的 module name 时，
# 无法在同一个 Verilator 编译单元中共存。
#
# 本脚本自动完成:
#   1. 读取 sram_instances.yaml 配置文件
#   2. 对每个 enabled 的实例:
#      a. 复制 orig RTL → gen/<name>_ori.sv, 重命名 module → <name>_ori
#      b. 复制 new  RTL → gen/<name>_new.sv, 重命名 module → <name>_new
#   3. 生成 Makefile 片段 (sram_b2b_list.mk) 供主 Makefile include
#   4. 生成回归脚本 (regress_sram_b2b.sh) 一键运行所有实例+测试
#
# 用法:
#   python3 scripts/gen_sram_b2b.py                      # 生成所有文件
#   python3 scripts/gen_sram_b2b.py --dry-run            # 预览，不实际写文件
#   python3 scripts/gen_sram_b2b.py --instance cpu_sys   # 只生成指定实例
# ============================================================

import os
import re
import sys
import argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip3 install pyyaml")
    sys.exit(1)


# ============================================================
# Config
# ============================================================
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJ_ROOT  = SCRIPT_DIR.parent
CONFIG_YAML = PROJ_ROOT / "sram_instances.yaml"


def load_config(path: Path) -> dict:
    """加载 YAML 配置文件"""
    with open(path, "r") as f:
        return yaml.safe_load(f)


def rename_module_in_file(src_path: Path, old_name: str, new_name: str, dst_path: Path) -> bool:
    """复制文件并替换 module name
    
    替换规则:
      - module <old_name>  →  module <new_name>
      - endmodule           →  endmodule  // <new_name> (添加注释方便调试)
    
    Returns: True on success
    """
    if not src_path.exists():
        print(f"  ERROR: Source file not found: {src_path}")
        return False

    content = src_path.read_text(encoding="utf-8", errors="replace")

    # 1. 替换 module 声明
    pattern = re.compile(r'\bmodule\s+' + re.escape(old_name) + r'\b')
    if not pattern.search(content):
        print(f"  WARNING: Could not find 'module {old_name}' in {src_path}")
    new_content = pattern.sub(f'module {new_name}', content)

    # 2. 替换 endmodule 注释
    new_content = re.sub(r'\bendmodule\b', f'endmodule  // {new_name}', new_content)

    dst_path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"// ============================================================\n"
        f"// AUTO-GENERATED by gen_sram_b2b.py - DO NOT EDIT MANUALLY\n"
        f"// Source: {src_path}\n"
        f"// Module: {old_name} -> {new_name}\n"
        f"// ============================================================\n"
    )
    final = header + new_content
    dst_path.write_text(final, encoding="utf-8")
    return True


def generate_connect_snippet(ori_module: str, new_module: str,
                              instance_name: str,
                              addr_width: int, data_width: int,
                              read_latency: int = 1) -> str:
    """Generate a unified `include connect snippet for tb_top.
    
    Contains ALL three instantiations in ONE file:
      - DUT original  (rdata → vif.rdata_*_ori)
      - DUT new       (rdata → vif.rdata_*_new)
      - SVA Checker   (vif)
    
    This way waveform shows DUTs + checker side-by-side.
    """

    lines = []
    lines.append("// ============================================================")
    lines.append(f"// AUTO-GENERATED B2B connect — `include in tb_top")
    lines.append(f"// Instance: {instance_name}")
    lines.append(f"// Ori:      {ori_module}")
    lines.append(f"// New:      {new_module}")
    lines.append(f"// Config:   AW={addr_width} DW={data_width}")
    lines.append("// ============================================================")
    lines.append("")

    # ── DUT Original ──
    lines.append("// ──────────────────────────────────────────────")
    lines.append(f"// DUT Original: {ori_module}")
    lines.append("// ──────────────────────────────────────────────")
    lines.append(f"{ori_module} #(")
    lines.append(f"    .ADDR_WIDTH ({addr_width}),")
    lines.append(f"    .DATA_WIDTH ({data_width})")
    lines.append(f") u_dut_ori (")
    lines.extend([
        "    .clk     (clk),",
        "    .rst_n   (rst_n),",
        "",
        "    // Port A",
        "    .cmd_a   (vif.cmd_a),",
        "    .addr_a  (vif.addr_a),",
        "    .wdata_a (vif.wdata_a),",
        "    .wem_a   (vif.wem_a),",
        "    .rdata_a (vif.rdata_a_ori),",
        "",
        "    // Port B",
        "    .cmd_b   (vif.cmd_b),",
        "    .addr_b  (vif.addr_b),",
        "    .wdata_b (vif.wdata_b),",
        "    .wem_b   (vif.wem_b),",
        "    .rdata_b (vif.rdata_b_ori)",
    ])
    lines.append(");")
    lines.append("")

    # ── DUT New ──
    lines.append("// ──────────────────────────────────────────────")
    lines.append(f"// DUT New: {new_module}")
    lines.append("// ──────────────────────────────────────────────")
    lines.append(f"{new_module} #(")
    lines.append(f"    .ADDR_WIDTH ({addr_width}),")
    lines.append(f"    .DATA_WIDTH ({data_width})")
    lines.append(f") u_dut_new (")
    lines.extend([
        "    .clk     (clk),",
        "    .rst_n   (rst_n),",
        "",
        "    // Port A",
        "    .cmd_a   (vif.cmd_a),",
        "    .addr_a  (vif.addr_a),",
        "    .wdata_a (vif.wdata_a),",
        "    .wem_a   (vif.wem_a),",
        "    .rdata_a (vif.rdata_a_new),",
        "",
        "    // Port B",
        "    .cmd_b   (vif.cmd_b),",
        "    .addr_b  (vif.addr_b),",
        "    .wdata_b (vif.wdata_b),",
        "    .wem_b   (vif.wem_b),",
        "    .rdata_b (vif.rdata_b_new)",
    ])
    lines.append(");")
    lines.append("")

    # ── SVA Checker ──
    lines.append("// ──────────────────────────────────────────────")
    lines.append("// SVA Checker: compares rdata_ori === rdata_new")
    lines.append("// ──────────────────────────────────────────────")
    lines.append(f"mem_sva_checker #(")
    lines.append(f"    .ADDR_WIDTH  ({addr_width}),")
    lines.append(f"    .DATA_WIDTH  ({data_width}),")
    lines.append(f"    .READ_LATENCY({read_latency})")
    lines.append(f") u_sva_checker (vif);")
    lines.append("")

    return "\n".join(lines)


def generate_makefile_frag(instances: list, cfg: dict, enabled_only: bool = True) -> str:
    """生成 Makefile 片段"""
    out_dir = cfg["global"]["output_dir"]
    lines = []
    lines.append("# ============================================================")
    lines.append(f"# AUTO-GENERATED by gen_sram_b2b.py")
    lines.append(f"# {len(instances)} SRAM instances registered")
    lines.append("# ============================================================")
    lines.append("")

    # Collect all generated DUT source files (renamed modules)
    dut_srcs = []
    connect_files = []
    for inst in instances:
        if enabled_only and not inst.get("enabled", True):
            continue
        name = inst["name"]
        dut_srcs.append(f"{out_dir}/{name}_ori.sv")
        dut_srcs.append(f"{out_dir}/{name}_new.sv")
        connect_files.append(f"{out_dir}/{name}_connect.sv")

    lines.append("# All generated DUT source files (renamed modules)")
    lines.append("GEN_DUT_SRCS = \\")
    for i, s in enumerate(dut_srcs):
        sep = " \\" if i < len(dut_srcs) - 1 else ""
        lines.append(f"    {s}{sep}")
    lines.append("")

    lines.append("# All generated unified connect `include snippets (ori + new + checker)")
    lines.append("GEN_CONNECT_SRCS = \\")
    for i, s in enumerate(connect_files):
        sep = " \\" if i < len(connect_files) - 1 else ""
        lines.append(f"    {s}{sep}")
    lines.append("")

    # Per-instance variables
    lines.append("# Per-instance DUT module names and connect files")
    for i, inst in enumerate(instances):
        if enabled_only and not inst.get("enabled", True):
            continue
        name = inst["name"]
        lines.append(f"# Instance [{i}]: {name}")
        lines.append(f"DUT_ORI_{name} = {name}_ori")
        lines.append(f"DUT_NEW_{name} = {name}_new")
        lines.append(f"AW_{name}     = {inst['addr_width']}")
        lines.append(f"DW_{name}     = {inst['data_width']}")
        lines.append(f"CONNECT_{name} = {out_dir}/{name}_connect.sv")
        lines.append("")

    # Convenience: list of all enabled instance names
    enabled_names = [
        inst["name"] for inst in instances
        if enabled_only and inst.get("enabled", True)
    ]
    lines.append(f"# All enabled instance names (space-separated)")
    lines.append(f"GEN_INSTANCES = {' '.join(enabled_names)}")
    lines.append("")

    # Test targets per instance
    lines.append("# ============================================================")
    lines.append("# Per-Instance Test Targets")
    lines.append("# Usage: make test-<instance_name> TEST=mem_sdp_test")
    lines.append("# Symlinks the unified connect file (ori+new+checker) → dut_connect.sv")
    lines.append("# ============================================================")
    for name in enabled_names:
        lines.append(f".PHONY: test-{name}")
        lines.append(f"test-{name}:")
        lines.append(f"\t@ln -sf {name}_connect.sv {out_dir}/dut_connect.sv")
        lines.append(f"\t$(MAKE) clean build run \\")
        lines.append(f"\t\tDUT_ORI=$(DUT_ORI_{name}) \\")
        lines.append(f"\t\tDUT_NEW=$(DUT_NEW_{name}) \\")
        lines.append(f"\t\tADDR_WIDTH=$(AW_{name}) \\")
        lines.append(f"\t\tDATA_WIDTH=$(DW_{name}) \\")
        lines.append(f"\t\tDUT_SRCS=\"{out_dir}/{name}_ori.sv {out_dir}/{name}_new.sv\" \\")
        lines.append(f"\t\tTEST=$(TEST)")
        lines.append("")

    # Regression target
    lines.append("# ============================================================")
    lines.append("# Full B2B Regression (all instances × all tests)")
    lines.append("# ============================================================")
    lines.append(".PHONY: regress-b2b")
    lines.append("regress-b2b:")
    lines.append(f"\t@bash {out_dir}/regress_sram_b2b.sh $$(TX_COUNT)")
    lines.append("")

    return "\n".join(lines)


def generate_regress_script(instances: list, cfg: dict, enabled_only: bool = True) -> str:
    """生成回归 shell 脚本"""
    out_dir = cfg["global"]["output_dir"]
    lines = []
    lines.append("#!/bin/bash")
    lines.append("# ============================================================")
    lines.append(f"# AUTO-GENERATED by gen_sram_b2b.py")
    lines.append("# SRAM B2B Full Regression Script")
    lines.append("# ============================================================")
    lines.append("set -e")
    lines.append("")
    lines.append('TX_COUNT="${1:-100}"')
    lines.append('RUN_DIR="${RUN_DIR:-run_dir}"')
    lines.append("LOG_DIR=\"run_dir/logs\"")
    lines.append("mkdir -p \"$LOG_DIR\"")
    lines.append("")

    # Test list
    lines.append("TESTS=(")
    lines.append('    "mem_sp_test"')
    lines.append('    "mem_sdp_test"')
    lines.append('    "mem_tdp_test"')
    lines.append('    "mem_wem_walking_test"')
    lines.append('    "mem_b2b_raw_test"')
    lines.append(")")
    lines.append("")

    lines.append("TOTAL_PASS=0")
    lines.append("TOTAL_FAIL=0")
    lines.append("")

    # Per-instance loop
    for inst in instances:
        if enabled_only and not inst.get("enabled", True):
            continue
        name = inst["name"]
        aw = inst["addr_width"]
        dw = inst["data_width"]
        lines.append(f"# ------------------------------------------------------")
        lines.append(f"# Instance: {name}  ({1 << aw}x{dw}, AW={aw}, DW={dw})")
        lines.append(f"# ------------------------------------------------------")
        lines.append(f"echo \"\"")
        lines.append(f"echo \"===== Instance: {name} (AW={aw} DW={dw}) =====\"")
        lines.append(f"make clean build \\")
        lines.append(f"    DUT_ORI={name}_ori \\")
        lines.append(f"    DUT_NEW={name}_new \\")
        lines.append(f"    ADDR_WIDTH={aw} \\")
        lines.append(f"    DATA_WIDTH={dw} \\")
        lines.append(f"    DUT_SRCS=\"{out_dir}/{name}_ori.sv {out_dir}/{name}_new.sv\"")
        lines.append(f"if [ $? -ne 0 ]; then")
        lines.append(f"    echo \"BUILD FAILED for {name}\"")
        lines.append(f"    TOTAL_FAIL=$((TOTAL_FAIL + 1))")
        lines.append(f"    continue")
        lines.append(f"fi")
        lines.append("")
        lines.append(f"for t in \"${{TESTS[@]}}\"; do")
        lines.append(f'    LOG="$LOG_DIR/${{t}}_{name}.log"')
        lines.append(f'    echo -n "  $t ... "')
        lines.append(f'    cd "$RUN_DIR" && ./Vtb_top +TEST="$t" +TX_COUNT="$TX_COUNT" > "../$LOG" 2>&1')
        lines.append(f'    if grep -Eq "SVA ERROR|ERROR" "../$LOG"; then')
        lines.append(f'        echo "FAIL"')
        lines.append(f'        TOTAL_FAIL=$((TOTAL_FAIL + 1))')
        lines.append(f'    else')
        lines.append(f'        echo "PASS"')
        lines.append(f'        TOTAL_PASS=$((TOTAL_PASS + 1))')
        lines.append(f'    fi')
        lines.append(f"done")
        lines.append("")

    lines.append("echo \"\"")
    lines.append('echo "============================================================"')
    lines.append('echo "B2B Regression Summary"')
    lines.append('echo "  PASSED: $TOTAL_PASS"')
    lines.append('echo "  FAILED: $TOTAL_FAIL"')
    lines.append('echo "  TOTAL:  $((TOTAL_PASS + TOTAL_FAIL))"')
    lines.append('echo "Logs: $LOG_DIR/"')
    lines.append('echo "============================================================"')
    lines.append("")
    lines.append("exit $TOTAL_FAIL")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="SRAM Back-to-Back 文件自动生成器"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="预览模式，不实际写文件"
    )
    parser.add_argument(
        "--instance", type=str, default=None,
        help="只处理指定 instance (按 name 过滤)"
    )
    parser.add_argument(
        "--config", type=str, default=str(CONFIG_YAML),
        help=f"配置文件路径 (默认: {CONFIG_YAML})"
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"ERROR: Config file not found: {config_path}")
        sys.exit(1)

    cfg = load_config(config_path)
    instances = cfg.get("instances", [])
    global_cfg = cfg.get("global", {})

    out_dir = PROJ_ROOT / global_cfg.get("output_dir", "gen")
    ori_suffix = global_cfg.get("ori_suffix", "_ori")
    new_suffix = global_cfg.get("new_suffix", "_new")

    # Filter by instance name
    if args.instance:
        instances = [i for i in instances if args.instance in i["name"]]
        if not instances:
            print(f"ERROR: No instance matching '{args.instance}' found")
            sys.exit(1)

    enabled_instances = [i for i in instances if i.get("enabled", True)]
    disabled_instances = [i for i in instances if not i.get("enabled", True)]

    print("=" * 60)
    print("SRAM B2B Generator")
    print(f"  Config:    {config_path}")
    print(f"  Output:    {out_dir}/")
    print(f"  Instances: {len(enabled_instances)} enabled, {len(disabled_instances)} disabled")
    print("=" * 60)

    if args.dry_run:
        print("\n>>> DRY RUN MODE - No files will be written <<<\n")

    # Phase 1: Generate renamed module files
    ok_count = 0
    fail_count = 0

    for inst in enabled_instances:
        name = inst["name"]
        mod_name = inst.get("module_name", name)
        orig_path = PROJ_ROOT / inst["orig_path"]
        new_path  = PROJ_ROOT / inst["new_path"]

        print(f"\n[{name}]")
        print(f"  Module: {mod_name}")
        print(f"  Orig:   {orig_path}")
        print(f"  New:    {new_path}")
        print(f"  Config: AW={inst['addr_width']}, DW={inst['data_width']}")

        ori_mod = f"{mod_name}{ori_suffix}"
        new_mod = f"{mod_name}{new_suffix}"

        dst_ori = out_dir / f"{name}_ori.sv"
        dst_new = out_dir / f"{name}_new.sv"

        if not args.dry_run:
            # Original → _ori
            if rename_module_in_file(orig_path, mod_name, ori_mod, dst_ori):
                print(f"  ✓  {dst_ori.name}  ({mod_name} → {ori_mod})")
                ok_count += 1
            else:
                fail_count += 1

            # New → _new
            if rename_module_in_file(new_path, mod_name, new_mod, dst_new):
                print(f"  ✓  {dst_new.name}  ({mod_name} → {new_mod})")
                ok_count += 1
            else:
                fail_count += 1
        else:
            print(f"  [DRY-RUN] Would create: {dst_ori}  ({mod_name} → {ori_mod})")
            print(f"  [DRY-RUN] Would create: {dst_new}  ({mod_name} → {new_mod})")
            ok_count += 2

    if fail_count > 0:
        print(f"\nERROR: {fail_count} file(s) failed.")
        sys.exit(1)

    # Phase 2: Generate unified connect `include snippets (ori + new + checker)
    print(f"\n{'='*60}")
    print("Phase 2: Generating unified connect `include snippets")
    print("         (ori + new + checker in one file)")
    print(f"{'='*60}")
    for inst in enabled_instances:
        name = inst["name"]
        ori_mod = f"{inst.get('module_name', name)}{ori_suffix}"
        new_mod = f"{inst.get('module_name', name)}{new_suffix}"
        aw = inst["addr_width"]
        dw = inst["data_width"]

        connect_sv = generate_connect_snippet(ori_mod, new_mod, name, aw, dw)
        connect_path = out_dir / f"{name}_connect.sv"
        if not args.dry_run:
            connect_path.write_text(connect_sv, encoding="utf-8")
            print(f"  ✓  {connect_path.name}  ({ori_mod} + {new_mod} + checker)")
        else:
            print(f"  [DRY-RUN] Would create: {connect_path.name}")

    # Phase 3: Generate Makefile fragment
    mk_frag = PROJ_ROOT / global_cfg.get("makefile_frag", "gen/sram_b2b_list.mk")
    mk_content = generate_makefile_frag(instances, cfg)
    if not args.dry_run:
        mk_frag.parent.mkdir(parents=True, exist_ok=True)
        mk_frag.write_text(mk_content, encoding="utf-8")
        print(f"\n✓  Makefile fragment: {mk_frag}")
    else:
        print(f"\n[DRY-RUN] Would create: {mk_frag}")

    # Phase 3: Generate regression script
    reg_script = PROJ_ROOT / global_cfg.get("regress_script", "gen/regress_sram_b2b.sh")
    reg_content = generate_regress_script(instances, cfg)
    if not args.dry_run:
        reg_script.parent.mkdir(parents=True, exist_ok=True)
        reg_script.write_text(reg_content, encoding="utf-8")
        reg_script.chmod(0o755)
        print(f"✓  Regression script: {reg_script}")
    else:
        print(f"[DRY-RUN] Would create: {reg_script}")

    # Summary
    print(f"\n{'='*60}")
    print(f"Done. {ok_count} files generated for {len(enabled_instances)} instance(s).")
    print(f"\nNext steps:")
    print(f"  1. Verify generated files in {out_dir}/")
    print(f"  2. Run single instance test:")
    for inst in enabled_instances[:3]:  # show first 3
        print(f"     make test-{inst['name']} TEST=mem_sdp_test")
    if len(enabled_instances) > 3:
        print(f"     ... and {len(enabled_instances)-3} more")
    print(f"  3. Run full regression:")
    print(f"     make regress-b2b TX_COUNT=200")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
